/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from 'ethers';
import type { IRouterAbi, IRouterAbiInterface } from '../IRouterAbi';

const _abi = [
  {
    type: 'function',
    name: 'createSubscriptionDelegatee',
    inputs: [
      {
        name: 'nonce',
        type: 'uint32',
        internalType: 'uint32',
      },
      {
        name: 'expiry',
        type: 'uint32',
        internalType: 'uint32',
      },
      {
        name: 'sub',
        type: 'tuple',
        internalType: 'struct ComputeSubscription',
        components: [
          {
            name: 'routeId',
            type: 'bytes32',
            internalType: 'bytes32',
          },
          {
            name: 'containerId',
            type: 'bytes32',
            internalType: 'bytes32',
          },
          {
            name: 'feeAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'client',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'activeAt',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'intervalSeconds',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'maxExecutions',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'wallet',
            type: 'address',
            internalType: 'address payable',
          },
          {
            name: 'feeToken',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'verifier',
            type: 'address',
            internalType: 'address payable',
          },
          {
            name: 'redundancy',
            type: 'uint16',
            internalType: 'uint16',
          },
          {
            name: 'useDeliveryInbox',
            type: 'bool',
            internalType: 'bool',
          },
        ],
      },
      {
        name: 'signature',
        type: 'bytes',
        internalType: 'bytes',
      },
    ],
    outputs: [
      {
        name: 'subscriptionId',
        type: 'uint64',
        internalType: 'uint64',
      },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'fulfill',
    inputs: [
      {
        name: 'input',
        type: 'bytes',
        internalType: 'bytes',
      },
      {
        name: 'output',
        type: 'bytes',
        internalType: 'bytes',
      },
      {
        name: 'proof',
        type: 'bytes',
        internalType: 'bytes',
      },
      {
        name: 'numRedundantDeliveries',
        type: 'uint16',
        internalType: 'uint16',
      },
      {
        name: 'nodeWallet',
        type: 'address',
        internalType: 'address',
      },
      {
        name: 'payments',
        type: 'tuple[]',
        internalType: 'struct Payment[]',
        components: [
          {
            name: 'recipient',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'feeToken',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'feeAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
        ],
      },
      {
        name: 'commitment',
        type: 'tuple',
        internalType: 'struct Commitment',
        components: [
          {
            name: 'requestId',
            type: 'bytes32',
            internalType: 'bytes32',
          },
          {
            name: 'subscriptionId',
            type: 'uint64',
            internalType: 'uint64',
          },
          {
            name: 'containerId',
            type: 'bytes32',
            internalType: 'bytes32',
          },
          {
            name: 'interval',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'useDeliveryInbox',
            type: 'bool',
            internalType: 'bool',
          },
          {
            name: 'redundancy',
            type: 'uint16',
            internalType: 'uint16',
          },
          {
            name: 'walletAddress',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'feeAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'feeToken',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'verifier',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'coordinator',
            type: 'address',
            internalType: 'address',
          },
        ],
      },
    ],
    outputs: [
      {
        name: 'resultCode',
        type: 'uint8',
        internalType: 'enum FulfillResult',
      },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getContractById',
    inputs: [
      {
        name: 'id',
        type: 'bytes32',
        internalType: 'bytes32',
      },
    ],
    outputs: [
      {
        name: 'addr',
        type: 'address',
        internalType: 'address',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getLastSubscriptionId',
    inputs: [],
    outputs: [
      {
        name: 'lastId',
        type: 'uint64',
        internalType: 'uint64',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getProposedContractById',
    inputs: [
      {
        name: 'id',
        type: 'bytes32',
        internalType: 'bytes32',
      },
    ],
    outputs: [
      {
        name: 'addr',
        type: 'address',
        internalType: 'address',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getWalletFactory',
    inputs: [],
    outputs: [
      {
        name: 'factory',
        type: 'address',
        internalType: 'address',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'hasSubscriptionNextInterval',
    inputs: [
      {
        name: 'subscriptionId',
        type: 'uint64',
        internalType: 'uint64',
      },
      {
        name: 'currentInterval',
        type: 'uint32',
        internalType: 'uint32',
      },
    ],
    outputs: [
      {
        name: 'hasNext',
        type: 'bool',
        internalType: 'bool',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isValidWallet',
    inputs: [
      {
        name: 'walletAddr',
        type: 'address',
        internalType: 'address',
      },
    ],
    outputs: [
      {
        name: 'isValid',
        type: 'bool',
        internalType: 'bool',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'lockForVerification',
    inputs: [
      {
        name: 'proofRequest',
        type: 'tuple',
        internalType: 'struct ProofVerificationRequest',
        components: [
          {
            name: 'subscriptionId',
            type: 'uint64',
            internalType: 'uint64',
          },
          {
            name: 'interval',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'submitterAddress',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'submitterWallet',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'escrowedAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'escrowToken',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'slashAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'expiry',
            type: 'uint32',
            internalType: 'uint32',
          },
        ],
      },
      {
        name: 'commitmentHash',
        type: 'bytes32',
        internalType: 'bytes32',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'pause',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'payFromCoordinator',
    inputs: [
      {
        name: 'subscriptionId',
        type: 'uint64',
        internalType: 'uint64',
      },
      {
        name: 'spenderWallet',
        type: 'address',
        internalType: 'address',
      },
      {
        name: 'spenderAddress',
        type: 'address',
        internalType: 'address',
      },
      {
        name: 'payments',
        type: 'tuple[]',
        internalType: 'struct Payment[]',
        components: [
          {
            name: 'recipient',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'feeToken',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'feeAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'prepareNodeVerification',
    inputs: [
      {
        name: 'subscriptionId',
        type: 'uint64',
        internalType: 'uint64',
      },
      {
        name: 'nextInterval',
        type: 'uint32',
        internalType: 'uint32',
      },
      {
        name: 'nodeWallet',
        type: 'address',
        internalType: 'address',
      },
      {
        name: 'token',
        type: 'address',
        internalType: 'address',
      },
      {
        name: 'amount',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'proposeContractsUpdate',
    inputs: [
      {
        name: 'proposalSetIds',
        type: 'bytes32[]',
        internalType: 'bytes32[]',
      },
      {
        name: 'proposalSetAddresses',
        type: 'address[]',
        internalType: 'address[]',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'sendRequest',
    inputs: [
      {
        name: 'subscriptionId',
        type: 'uint64',
        internalType: 'uint64',
      },
      {
        name: 'interval',
        type: 'uint32',
        internalType: 'uint32',
      },
    ],
    outputs: [
      {
        name: 'requestKey',
        type: 'bytes32',
        internalType: 'bytes32',
      },
      {
        name: 'commitment',
        type: 'tuple',
        internalType: 'struct Commitment',
        components: [
          {
            name: 'requestId',
            type: 'bytes32',
            internalType: 'bytes32',
          },
          {
            name: 'subscriptionId',
            type: 'uint64',
            internalType: 'uint64',
          },
          {
            name: 'containerId',
            type: 'bytes32',
            internalType: 'bytes32',
          },
          {
            name: 'interval',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'useDeliveryInbox',
            type: 'bool',
            internalType: 'bool',
          },
          {
            name: 'redundancy',
            type: 'uint16',
            internalType: 'uint16',
          },
          {
            name: 'walletAddress',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'feeAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'feeToken',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'verifier',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'coordinator',
            type: 'address',
            internalType: 'address',
          },
        ],
      },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'timeoutRequest',
    inputs: [
      {
        name: 'requestId',
        type: 'bytes32',
        internalType: 'bytes32',
      },
      {
        name: 'subscriptionId',
        type: 'uint64',
        internalType: 'uint64',
      },
      {
        name: 'interval',
        type: 'uint32',
        internalType: 'uint32',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'unlockForVerification',
    inputs: [
      {
        name: 'proofRequest',
        type: 'tuple',
        internalType: 'struct ProofVerificationRequest',
        components: [
          {
            name: 'subscriptionId',
            type: 'uint64',
            internalType: 'uint64',
          },
          {
            name: 'interval',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'submitterAddress',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'submitterWallet',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'escrowedAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'escrowToken',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'slashAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'expiry',
            type: 'uint32',
            internalType: 'uint32',
          },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'unpause',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updateContracts',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
] as const;

export class IRouterAbi__factory {
  static readonly abi = _abi;
  static createInterface(): IRouterAbiInterface {
    return new Interface(_abi) as IRouterAbiInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IRouterAbi {
    return new Contract(address, _abi, runner) as unknown as IRouterAbi;
  }
}
