/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from 'ethers';
import type { RouterAbi, RouterAbiInterface } from '../RouterAbi';

const _abi = [
  {
    type: 'constructor',
    inputs: [
      {
        name: '_initialOwner',
        type: 'address',
        internalType: 'address',
      },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'EIP712_NAME',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'string',
        internalType: 'string',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'EIP712_VERSION',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'string',
        internalType: 'string',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'acceptOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'cancelComputeSubscription',
    inputs: [
      {
        name: 'subscriptionId',
        type: 'uint64',
        internalType: 'uint64',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'client',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'createComputeSubscription',
    inputs: [
      {
        name: 'containerId',
        type: 'string',
        internalType: 'string',
      },
      {
        name: 'maxExecutions',
        type: 'uint32',
        internalType: 'uint32',
      },
      {
        name: 'intervalSeconds',
        type: 'uint32',
        internalType: 'uint32',
      },
      {
        name: 'redundancy',
        type: 'uint16',
        internalType: 'uint16',
      },
      {
        name: 'useDeliveryInbox',
        type: 'bool',
        internalType: 'bool',
      },
      {
        name: 'feeToken',
        type: 'address',
        internalType: 'address',
      },
      {
        name: 'feeAmount',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'wallet',
        type: 'address',
        internalType: 'address',
      },
      {
        name: 'verifier',
        type: 'address',
        internalType: 'address',
      },
      {
        name: 'routeId',
        type: 'bytes32',
        internalType: 'bytes32',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'uint64',
        internalType: 'uint64',
      },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'createSubscriptionDelegatee',
    inputs: [
      {
        name: 'nonce',
        type: 'uint32',
        internalType: 'uint32',
      },
      {
        name: 'expiry',
        type: 'uint32',
        internalType: 'uint32',
      },
      {
        name: 'sub',
        type: 'tuple',
        internalType: 'struct ComputeSubscription',
        components: [
          {
            name: 'routeId',
            type: 'bytes32',
            internalType: 'bytes32',
          },
          {
            name: 'containerId',
            type: 'bytes32',
            internalType: 'bytes32',
          },
          {
            name: 'feeAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'client',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'activeAt',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'intervalSeconds',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'maxExecutions',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'wallet',
            type: 'address',
            internalType: 'address payable',
          },
          {
            name: 'feeToken',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'verifier',
            type: 'address',
            internalType: 'address payable',
          },
          {
            name: 'redundancy',
            type: 'uint16',
            internalType: 'uint16',
          },
          {
            name: 'useDeliveryInbox',
            type: 'bool',
            internalType: 'bool',
          },
        ],
      },
      {
        name: 'signature',
        type: 'bytes',
        internalType: 'bytes',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'uint64',
        internalType: 'uint64',
      },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'createSubscriptionFor',
    inputs: [
      {
        name: 'sub',
        type: 'tuple',
        internalType: 'struct ComputeSubscription',
        components: [
          {
            name: 'routeId',
            type: 'bytes32',
            internalType: 'bytes32',
          },
          {
            name: 'containerId',
            type: 'bytes32',
            internalType: 'bytes32',
          },
          {
            name: 'feeAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'client',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'activeAt',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'intervalSeconds',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'maxExecutions',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'wallet',
            type: 'address',
            internalType: 'address payable',
          },
          {
            name: 'feeToken',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'verifier',
            type: 'address',
            internalType: 'address payable',
          },
          {
            name: 'redundancy',
            type: 'uint16',
            internalType: 'uint16',
          },
          {
            name: 'useDeliveryInbox',
            type: 'bool',
            internalType: 'bool',
          },
        ],
      },
    ],
    outputs: [
      {
        name: '',
        type: 'uint64',
        internalType: 'uint64',
      },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'delegateCreatedIds',
    inputs: [
      {
        name: '',
        type: 'bytes32',
        internalType: 'bytes32',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'uint64',
        internalType: 'uint64',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'eip712Domain',
    inputs: [],
    outputs: [
      {
        name: 'fields',
        type: 'bytes1',
        internalType: 'bytes1',
      },
      {
        name: 'name',
        type: 'string',
        internalType: 'string',
      },
      {
        name: 'version',
        type: 'string',
        internalType: 'string',
      },
      {
        name: 'chainId',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'verifyingContract',
        type: 'address',
        internalType: 'address',
      },
      {
        name: 'salt',
        type: 'bytes32',
        internalType: 'bytes32',
      },
      {
        name: 'extensions',
        type: 'uint256[]',
        internalType: 'uint256[]',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'fulfill',
    inputs: [
      {
        name: 'input',
        type: 'tuple',
        internalType: 'struct PayloadData',
        components: [
          {
            name: 'contentHash',
            type: 'bytes32',
            internalType: 'bytes32',
          },
          {
            name: 'uri',
            type: 'bytes',
            internalType: 'bytes',
          },
        ],
      },
      {
        name: 'output',
        type: 'tuple',
        internalType: 'struct PayloadData',
        components: [
          {
            name: 'contentHash',
            type: 'bytes32',
            internalType: 'bytes32',
          },
          {
            name: 'uri',
            type: 'bytes',
            internalType: 'bytes',
          },
        ],
      },
      {
        name: 'proof',
        type: 'tuple',
        internalType: 'struct PayloadData',
        components: [
          {
            name: 'contentHash',
            type: 'bytes32',
            internalType: 'bytes32',
          },
          {
            name: 'uri',
            type: 'bytes',
            internalType: 'bytes',
          },
        ],
      },
      {
        name: 'numRedundantDeliveries',
        type: 'uint16',
        internalType: 'uint16',
      },
      {
        name: 'nodeWallet',
        type: 'address',
        internalType: 'address',
      },
      {
        name: 'payments',
        type: 'tuple[]',
        internalType: 'struct Payment[]',
        components: [
          {
            name: 'recipient',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'feeToken',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'feeAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
        ],
      },
      {
        name: 'commitment',
        type: 'tuple',
        internalType: 'struct Commitment',
        components: [
          {
            name: 'requestId',
            type: 'bytes32',
            internalType: 'bytes32',
          },
          {
            name: 'subscriptionId',
            type: 'uint64',
            internalType: 'uint64',
          },
          {
            name: 'containerId',
            type: 'bytes32',
            internalType: 'bytes32',
          },
          {
            name: 'interval',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'useDeliveryInbox',
            type: 'bool',
            internalType: 'bool',
          },
          {
            name: 'redundancy',
            type: 'uint16',
            internalType: 'uint16',
          },
          {
            name: 'walletAddress',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'feeAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'feeToken',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'verifier',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'coordinator',
            type: 'address',
            internalType: 'address',
          },
        ],
      },
    ],
    outputs: [
      {
        name: 'resultCode',
        type: 'uint8',
        internalType: 'enum FulfillResult',
      },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getComputeSubscription',
    inputs: [
      {
        name: 'subscriptionId',
        type: 'uint64',
        internalType: 'uint64',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct ComputeSubscription',
        components: [
          {
            name: 'routeId',
            type: 'bytes32',
            internalType: 'bytes32',
          },
          {
            name: 'containerId',
            type: 'bytes32',
            internalType: 'bytes32',
          },
          {
            name: 'feeAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'client',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'activeAt',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'intervalSeconds',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'maxExecutions',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'wallet',
            type: 'address',
            internalType: 'address payable',
          },
          {
            name: 'feeToken',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'verifier',
            type: 'address',
            internalType: 'address payable',
          },
          {
            name: 'redundancy',
            type: 'uint16',
            internalType: 'uint16',
          },
          {
            name: 'useDeliveryInbox',
            type: 'bool',
            internalType: 'bool',
          },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getComputeSubscriptionInterval',
    inputs: [
      {
        name: 'subscriptionId',
        type: 'uint64',
        internalType: 'uint64',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'uint32',
        internalType: 'uint32',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getContractById',
    inputs: [
      {
        name: 'id',
        type: 'bytes32',
        internalType: 'bytes32',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getLastSubscriptionId',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint64',
        internalType: 'uint64',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getProposedContractById',
    inputs: [
      {
        name: 'id',
        type: 'bytes32',
        internalType: 'bytes32',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getWalletFactory',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'hasSubscriptionNextInterval',
    inputs: [
      {
        name: 'subscriptionId',
        type: 'uint64',
        internalType: 'uint64',
      },
      {
        name: 'currentInterval',
        type: 'uint32',
        internalType: 'uint32',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
        internalType: 'bool',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isValidWallet',
    inputs: [
      {
        name: 'walletAddr',
        type: 'address',
        internalType: 'address',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
        internalType: 'bool',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'lockForVerification',
    inputs: [
      {
        name: 'proofRequest',
        type: 'tuple',
        internalType: 'struct ProofVerificationRequest',
        components: [
          {
            name: 'subscriptionId',
            type: 'uint64',
            internalType: 'uint64',
          },
          {
            name: 'interval',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'submitterAddress',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'submitterWallet',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'escrowedAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'escrowToken',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'slashAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'expiry',
            type: 'uint32',
            internalType: 'uint32',
          },
        ],
      },
      {
        name: 'commitmentHash',
        type: 'bytes32',
        internalType: 'bytes32',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'maxSubscriberNonce',
    inputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'uint32',
        internalType: 'uint32',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'minRepeatInterval',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint32',
        internalType: 'uint32',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'ownerCancelSubscription',
    inputs: [
      {
        name: 'subscriptionId',
        type: 'uint64',
        internalType: 'uint64',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'pause',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'paused',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'bool',
        internalType: 'bool',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'payFromCoordinator',
    inputs: [
      {
        name: 'subscriptionId',
        type: 'uint64',
        internalType: 'uint64',
      },
      {
        name: 'spenderWallet',
        type: 'address',
        internalType: 'address',
      },
      {
        name: 'spenderAddress',
        type: 'address',
        internalType: 'address',
      },
      {
        name: 'payments',
        type: 'tuple[]',
        internalType: 'struct Payment[]',
        components: [
          {
            name: 'recipient',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'feeToken',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'feeAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'pendingRequestExists',
    inputs: [
      {
        name: 'subscriptionId',
        type: 'uint64',
        internalType: 'uint64',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
        internalType: 'bool',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'prepareNodeVerification',
    inputs: [
      {
        name: 'subscriptionId',
        type: 'uint64',
        internalType: 'uint64',
      },
      {
        name: 'nextInterval',
        type: 'uint32',
        internalType: 'uint32',
      },
      {
        name: 'nodeWallet',
        type: 'address',
        internalType: 'address',
      },
      {
        name: 'token',
        type: 'address',
        internalType: 'address',
      },
      {
        name: 'amount',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'proposeContractsUpdate',
    inputs: [
      {
        name: 'proposalSetIds',
        type: 'bytes32[]',
        internalType: 'bytes32[]',
      },
      {
        name: 'proposalSetAddresses',
        type: 'address[]',
        internalType: 'address[]',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'sendRequest',
    inputs: [
      {
        name: 'subscriptionId',
        type: 'uint64',
        internalType: 'uint64',
      },
      {
        name: 'interval',
        type: 'uint32',
        internalType: 'uint32',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
        internalType: 'bytes32',
      },
      {
        name: '',
        type: 'tuple',
        internalType: 'struct Commitment',
        components: [
          {
            name: 'requestId',
            type: 'bytes32',
            internalType: 'bytes32',
          },
          {
            name: 'subscriptionId',
            type: 'uint64',
            internalType: 'uint64',
          },
          {
            name: 'containerId',
            type: 'bytes32',
            internalType: 'bytes32',
          },
          {
            name: 'interval',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'useDeliveryInbox',
            type: 'bool',
            internalType: 'bool',
          },
          {
            name: 'redundancy',
            type: 'uint16',
            internalType: 'uint16',
          },
          {
            name: 'walletAddress',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'feeAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'feeToken',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'verifier',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'coordinator',
            type: 'address',
            internalType: 'address',
          },
        ],
      },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setMinRepeatInterval',
    inputs: [
      {
        name: '_minRepeatInterval',
        type: 'uint32',
        internalType: 'uint32',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setWalletFactory',
    inputs: [
      {
        name: '_walletFactory',
        type: 'address',
        internalType: 'address',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'timeoutRequest',
    inputs: [
      {
        name: 'requestId',
        type: 'bytes32',
        internalType: 'bytes32',
      },
      {
        name: 'subscriptionId',
        type: 'uint64',
        internalType: 'uint64',
      },
      {
        name: 'interval',
        type: 'uint32',
        internalType: 'uint32',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'timeoutSubscriptionIntervalsUpTo',
    inputs: [
      {
        name: 'subscriptionId',
        type: 'uint64',
        internalType: 'uint64',
      },
      {
        name: 'uptoInterval',
        type: 'uint32',
        internalType: 'uint32',
      },
      {
        name: 'maxIter',
        type: 'uint32',
        internalType: 'uint32',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [
      {
        name: 'to',
        type: 'address',
        internalType: 'address',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'typeAndVersion',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'string',
        internalType: 'string',
      },
    ],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'unlockForVerification',
    inputs: [
      {
        name: 'proofRequest',
        type: 'tuple',
        internalType: 'struct ProofVerificationRequest',
        components: [
          {
            name: 'subscriptionId',
            type: 'uint64',
            internalType: 'uint64',
          },
          {
            name: 'interval',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'submitterAddress',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'submitterWallet',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'escrowedAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'escrowToken',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'slashAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'expiry',
            type: 'uint32',
            internalType: 'uint32',
          },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'unpause',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updateContracts',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'CommitmentTimedOut',
    inputs: [
      {
        name: 'requestId',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
      {
        name: 'subscriptionId',
        type: 'uint64',
        indexed: true,
        internalType: 'uint64',
      },
      {
        name: 'interval',
        type: 'uint32',
        indexed: true,
        internalType: 'uint32',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ContractsUpdateProposed',
    inputs: [
      {
        name: 'ids',
        type: 'bytes32[]',
        indexed: false,
        internalType: 'bytes32[]',
      },
      {
        name: 'addresses',
        type: 'address[]',
        indexed: false,
        internalType: 'address[]',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ContractsUpdated',
    inputs: [
      {
        name: 'id',
        type: 'bytes32',
        indexed: false,
        internalType: 'bytes32',
      },
      {
        name: 'contractAddress',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'EIP712DomainChanged',
    inputs: [],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MinRepeatIntervalSet',
    inputs: [
      {
        name: 'newMinRepeatInterval',
        type: 'uint32',
        indexed: false,
        internalType: 'uint32',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferRequested',
    inputs: [
      {
        name: 'from',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'to',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      {
        name: 'from',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'to',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Paused',
    inputs: [
      {
        name: 'account',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PaymentMade',
    inputs: [
      {
        name: 'subscriptionId',
        type: 'uint64',
        indexed: true,
        internalType: 'uint64',
      },
      {
        name: 'spenderWallet',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'recipient',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'token',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'amount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RequestProcessed',
    inputs: [
      {
        name: 'requestId',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
      {
        name: 'subscriptionId',
        type: 'uint64',
        indexed: true,
        internalType: 'uint64',
      },
      {
        name: 'containerId',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
      {
        name: 'interval',
        type: 'uint32',
        indexed: false,
        internalType: 'uint32',
      },
      {
        name: 'useDeliveryInbox',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
      {
        name: 'feeAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'feeToken',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'verifier',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'coordinator',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'nodeWallet',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'result',
        type: 'uint8',
        indexed: false,
        internalType: 'enum FulfillResult',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RequestStart',
    inputs: [
      {
        name: 'requestId',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
      {
        name: 'subscriptionId',
        type: 'uint64',
        indexed: true,
        internalType: 'uint64',
      },
      {
        name: 'containerId',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
      {
        name: 'interval',
        type: 'uint32',
        indexed: false,
        internalType: 'uint32',
      },
      {
        name: 'redundancy',
        type: 'uint16',
        indexed: false,
        internalType: 'uint16',
      },
      {
        name: 'useDeliveryInbox',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
      {
        name: 'feeAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'feeToken',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'verifier',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'coordinator',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SubscriptionCancelled',
    inputs: [
      {
        name: 'subscriptionId',
        type: 'uint64',
        indexed: true,
        internalType: 'uint64',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SubscriptionCreated',
    inputs: [
      {
        name: 'subscriptionId',
        type: 'uint64',
        indexed: true,
        internalType: 'uint64',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SubscriptionFulfilled',
    inputs: [
      {
        name: 'id',
        type: 'uint64',
        indexed: true,
        internalType: 'uint64',
      },
      {
        name: 'node',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Unpaused',
    inputs: [
      {
        name: 'account',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'VerificationFundsLocked',
    inputs: [
      {
        name: 'subscriptionId',
        type: 'uint64',
        indexed: true,
        internalType: 'uint64',
      },
      {
        name: 'interval',
        type: 'uint32',
        indexed: true,
        internalType: 'uint32',
      },
      {
        name: 'spender',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'amount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'VerificationFundsUnlocked',
    inputs: [
      {
        name: 'subscriptionId',
        type: 'uint64',
        indexed: true,
        internalType: 'uint64',
      },
      {
        name: 'interval',
        type: 'uint32',
        indexed: true,
        internalType: 'uint32',
      },
      {
        name: 'spender',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'amount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'error',
    name: 'CannotRemoveWithPendingRequests',
    inputs: [],
  },
  {
    type: 'error',
    name: 'CommitmentNotTimeoutable',
    inputs: [],
  },
  {
    type: 'error',
    name: 'DuplicateRequestId',
    inputs: [
      {
        name: 'requestId',
        type: 'bytes32',
        internalType: 'bytes32',
      },
    ],
  },
  {
    type: 'error',
    name: 'ECDSAInvalidSignature',
    inputs: [],
  },
  {
    type: 'error',
    name: 'ECDSAInvalidSignatureLength',
    inputs: [
      {
        name: 'length',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
  },
  {
    type: 'error',
    name: 'ECDSAInvalidSignatureS',
    inputs: [
      {
        name: 's',
        type: 'bytes32',
        internalType: 'bytes32',
      },
    ],
  },
  {
    type: 'error',
    name: 'EmptyRequestData',
    inputs: [],
  },
  {
    type: 'error',
    name: 'EnforcedPause',
    inputs: [],
  },
  {
    type: 'error',
    name: 'ExpectedPause',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InvalidProposedUpdate',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InvalidRequestCommitment',
    inputs: [
      {
        name: 'requestId',
        type: 'bytes32',
        internalType: 'bytes32',
      },
    ],
  },
  {
    type: 'error',
    name: 'InvalidShortString',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InvalidSubscription',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InvalidWallet',
    inputs: [],
  },
  {
    type: 'error',
    name: 'MismatchedRequestId',
    inputs: [],
  },
  {
    type: 'error',
    name: 'MismatchedSubscriptionId',
    inputs: [],
  },
  {
    type: 'error',
    name: 'NoSuchCommitment',
    inputs: [],
  },
  {
    type: 'error',
    name: 'NotPendingOwner',
    inputs: [],
  },
  {
    type: 'error',
    name: 'NotSubscriptionOwner',
    inputs: [],
  },
  {
    type: 'error',
    name: 'OnlyCallableByOwner',
    inputs: [],
  },
  {
    type: 'error',
    name: 'OnlyCallableFromCoordinator',
    inputs: [],
  },
  {
    type: 'error',
    name: 'ReentrancyGuardReentrantCall',
    inputs: [],
  },
  {
    type: 'error',
    name: 'RouteNotFound',
    inputs: [
      {
        name: 'id',
        type: 'bytes32',
        internalType: 'bytes32',
      },
    ],
  },
  {
    type: 'error',
    name: 'SignatureExpired',
    inputs: [],
  },
  {
    type: 'error',
    name: 'SignerMismatch',
    inputs: [],
  },
  {
    type: 'error',
    name: 'StringTooLong',
    inputs: [
      {
        name: 'str',
        type: 'string',
        internalType: 'string',
      },
    ],
  },
  {
    type: 'error',
    name: 'SubscriptionCompleted',
    inputs: [],
  },
  {
    type: 'error',
    name: 'SubscriptionIntervalTooShort',
    inputs: [
      {
        name: 'interval',
        type: 'uint32',
        internalType: 'uint32',
      },
      {
        name: 'minInterval',
        type: 'uint32',
        internalType: 'uint32',
      },
    ],
  },
  {
    type: 'error',
    name: 'SubscriptionNotActive',
    inputs: [],
  },
  {
    type: 'error',
    name: 'SubscriptionNotFound',
    inputs: [],
  },
  {
    type: 'error',
    name: 'TokenMismatch',
    inputs: [],
  },
] as const;

export class RouterAbi__factory {
  static readonly abi = _abi;
  static createInterface(): RouterAbiInterface {
    return new Interface(_abi) as RouterAbiInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): RouterAbi {
    return new Contract(address, _abi, runner) as unknown as RouterAbi;
  }
}
