/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  SubscriptionBatchReaderAbi,
  SubscriptionBatchReaderAbiInterface,
} from "../SubscriptionBatchReaderAbi";

const _abi = [
  {
    type: "constructor",
    inputs: [
      {
        name: "_router",
        type: "address",
        internalType: "address",
      },
      {
        name: "_coordinator",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getIntervalStatuses",
    inputs: [
      {
        name: "ids",
        type: "uint64[]",
        internalType: "uint64[]",
      },
      {
        name: "intervals",
        type: "uint32[]",
        internalType: "uint32[]",
      },
    ],
    outputs: [
      {
        name: "statuses",
        type: "tuple[]",
        internalType: "struct SubscriptionBatchReader.IntervalStatus[]",
        components: [
          {
            name: "commitmentExists",
            type: "bool",
            internalType: "bool",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getSubscriptions",
    inputs: [
      {
        name: "startId",
        type: "uint64",
        internalType: "uint64",
      },
      {
        name: "endId",
        type: "uint64",
        internalType: "uint64",
      },
    ],
    outputs: [
      {
        name: "subscriptions",
        type: "tuple[]",
        internalType: "struct ComputeSubscription[]",
        components: [
          {
            name: "routeId",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "containerId",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "feeAmount",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "client",
            type: "address",
            internalType: "address",
          },
          {
            name: "activeAt",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "intervalSeconds",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "maxExecutions",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "wallet",
            type: "address",
            internalType: "address payable",
          },
          {
            name: "feeToken",
            type: "address",
            internalType: "address",
          },
          {
            name: "verifier",
            type: "address",
            internalType: "address payable",
          },
          {
            name: "useDeliveryInbox",
            type: "bool",
            internalType: "bool",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
] as const;

export class SubscriptionBatchReaderAbi__factory {
  static readonly abi = _abi;
  static createInterface(): SubscriptionBatchReaderAbiInterface {
    return new Interface(_abi) as SubscriptionBatchReaderAbiInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SubscriptionBatchReaderAbi {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as SubscriptionBatchReaderAbi;
  }
}
