/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from 'ethers';
import type { WalletFactoryAbi, WalletFactoryAbiInterface } from '../WalletFactoryAbi';

const _abi = [
  {
    type: 'constructor',
    inputs: [
      {
        name: 'router',
        type: 'address',
        internalType: 'address',
      },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'createWallet',
    inputs: [
      {
        name: 'initialOwner',
        type: 'address',
        internalType: 'address',
      },
    ],
    outputs: [
      {
        name: 'walletAddr',
        type: 'address',
        internalType: 'address',
      },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'isValidWallet',
    inputs: [
      {
        name: 'walletAddr',
        type: 'address',
        internalType: 'address',
      },
    ],
    outputs: [
      {
        name: 'isCreated',
        type: 'bool',
        internalType: 'bool',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'typeAndVersion',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'string',
        internalType: 'string',
      },
    ],
    stateMutability: 'pure',
  },
  {
    type: 'event',
    name: 'WalletCreated',
    inputs: [
      {
        name: 'operator',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'owner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'walletAddress',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'error',
    name: 'OnlyCallableByRouter',
    inputs: [],
  },
  {
    type: 'error',
    name: 'OnlyCallableByRouterOwner',
    inputs: [],
  },
  {
    type: 'error',
    name: 'RouterMustBeSet',
    inputs: [],
  },
] as const;

export class WalletFactoryAbi__factory {
  static readonly abi = _abi;
  static createInterface(): WalletFactoryAbiInterface {
    return new Interface(_abi) as WalletFactoryAbiInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): WalletFactoryAbi {
    return new Contract(address, _abi, runner) as unknown as WalletFactoryAbi;
  }
}
