/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export type CommitmentStruct = {
  requestId: BytesLike;
  subscriptionId: BigNumberish;
  containerId: BytesLike;
  interval: BigNumberish;
  useDeliveryInbox: boolean;
  redundancy: BigNumberish;
  walletAddress: AddressLike;
  feeAmount: BigNumberish;
  feeToken: AddressLike;
  verifier: AddressLike;
  coordinator: AddressLike;
};

export type CommitmentStructOutput = [
  requestId: string,
  subscriptionId: bigint,
  containerId: string,
  interval: bigint,
  useDeliveryInbox: boolean,
  redundancy: bigint,
  walletAddress: string,
  feeAmount: bigint,
  feeToken: string,
  verifier: string,
  coordinator: string
] & {
  requestId: string;
  subscriptionId: bigint;
  containerId: string;
  interval: bigint;
  useDeliveryInbox: boolean;
  redundancy: bigint;
  walletAddress: string;
  feeAmount: bigint;
  feeToken: string;
  verifier: string;
  coordinator: string;
};

export type BillingConfigStruct = {
  verificationTimeout: BigNumberish;
  protocolFeeRecipient: AddressLike;
  protocolFee: BigNumberish;
  tickNodeFee: BigNumberish;
  tickNodeFeeToken: AddressLike;
};

export type BillingConfigStructOutput = [
  verificationTimeout: bigint,
  protocolFeeRecipient: string,
  protocolFee: bigint,
  tickNodeFee: bigint,
  tickNodeFeeToken: string
] & {
  verificationTimeout: bigint;
  protocolFeeRecipient: string;
  protocolFee: bigint;
  tickNodeFee: bigint;
  tickNodeFeeToken: string;
};

export type PayloadDataStruct = { contentHash: BytesLike; uri: BytesLike };

export type PayloadDataStructOutput = [contentHash: string, uri: string] & {
  contentHash: string;
  uri: string;
};

export type ProofVerificationRequestStruct = {
  subscriptionId: BigNumberish;
  interval: BigNumberish;
  submitterAddress: AddressLike;
  submitterWallet: AddressLike;
  escrowedAmount: BigNumberish;
  escrowToken: AddressLike;
  slashAmount: BigNumberish;
  expiry: BigNumberish;
};

export type ProofVerificationRequestStructOutput = [
  subscriptionId: bigint,
  interval: bigint,
  submitterAddress: string,
  submitterWallet: string,
  escrowedAmount: bigint,
  escrowToken: string,
  slashAmount: bigint,
  expiry: bigint
] & {
  subscriptionId: bigint;
  interval: bigint;
  submitterAddress: string;
  submitterWallet: string;
  escrowedAmount: bigint;
  escrowToken: string;
  slashAmount: bigint;
  expiry: bigint;
};

export interface CoordinatorAbiInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOwnership"
      | "cancelRequest"
      | "client"
      | "getCommitment"
      | "getConfig"
      | "getProtocolFee"
      | "getSubscriptionBatchReader"
      | "initialize"
      | "nodeResponded"
      | "prepareNextInterval"
      | "redundancyCount"
      | "reportComputeResult"
      | "reportVerificationResult"
      | "requestCommitments"
      | "setSubscriptionBatchReader"
      | "startRequest"
      | "transferOwnership"
      | "typeAndVersion"
      | "updateConfig"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ComputeDelivered"
      | "OwnershipTransferRequested"
      | "OwnershipTransferred"
      | "ProofVerified"
      | "RequestCancelled"
      | "RequestStarted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelRequest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "client", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCommitment",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getConfig", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getProtocolFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSubscriptionBatchReader",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [BillingConfigStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "nodeResponded",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "prepareNextInterval",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "redundancyCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reportComputeResult",
    values: [
      BigNumberish,
      PayloadDataStruct,
      PayloadDataStruct,
      PayloadDataStruct,
      BytesLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "reportVerificationResult",
    values: [ProofVerificationRequestStruct, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "requestCommitments",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSubscriptionBatchReader",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "startRequest",
    values: [
      BytesLike,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish,
      boolean,
      AddressLike,
      BigNumberish,
      AddressLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "typeAndVersion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateConfig",
    values: [BillingConfigStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "client", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getConfig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProtocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubscriptionBatchReader",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nodeResponded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "prepareNextInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redundancyCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reportComputeResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reportVerificationResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestCommitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSubscriptionBatchReader",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "typeAndVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateConfig",
    data: BytesLike
  ): Result;
}

export namespace ComputeDeliveredEvent {
  export type InputTuple = [
    requestId: BytesLike,
    nodeWallet: AddressLike,
    numRedundantDeliveries: BigNumberish,
    input: PayloadDataStruct,
    output: PayloadDataStruct,
    proof: PayloadDataStruct
  ];
  export type OutputTuple = [
    requestId: string,
    nodeWallet: string,
    numRedundantDeliveries: bigint,
    input: PayloadDataStructOutput,
    output: PayloadDataStructOutput,
    proof: PayloadDataStructOutput
  ];
  export interface OutputObject {
    requestId: string;
    nodeWallet: string;
    numRedundantDeliveries: bigint;
    input: PayloadDataStructOutput;
    output: PayloadDataStructOutput;
    proof: PayloadDataStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferRequestedEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike];
  export type OutputTuple = [from: string, to: string];
  export interface OutputObject {
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike];
  export type OutputTuple = [from: string, to: string];
  export interface OutputObject {
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofVerifiedEvent {
  export type InputTuple = [
    subscriptionId: BigNumberish,
    interval: BigNumberish,
    node: AddressLike,
    valid: boolean,
    verifier: AddressLike
  ];
  export type OutputTuple = [
    subscriptionId: bigint,
    interval: bigint,
    node: string,
    valid: boolean,
    verifier: string
  ];
  export interface OutputObject {
    subscriptionId: bigint;
    interval: bigint;
    node: string;
    valid: boolean;
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestCancelledEvent {
  export type InputTuple = [requestId: BytesLike];
  export type OutputTuple = [requestId: string];
  export interface OutputObject {
    requestId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestStartedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    subscriptionId: BigNumberish,
    containerId: BytesLike,
    commitment: CommitmentStruct
  ];
  export type OutputTuple = [
    requestId: string,
    subscriptionId: bigint,
    containerId: string,
    commitment: CommitmentStructOutput
  ];
  export interface OutputObject {
    requestId: string;
    subscriptionId: bigint;
    containerId: string;
    commitment: CommitmentStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CoordinatorAbi extends BaseContract {
  connect(runner?: ContractRunner | null): CoordinatorAbi;
  waitForDeployment(): Promise<this>;

  interface: CoordinatorAbiInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  cancelRequest: TypedContractMethod<
    [requestId: BytesLike],
    [void],
    "nonpayable"
  >;

  client: TypedContractMethod<[], [string], "view">;

  getCommitment: TypedContractMethod<
    [subscriptionId: BigNumberish, interval: BigNumberish],
    [CommitmentStructOutput],
    "view"
  >;

  getConfig: TypedContractMethod<[], [BillingConfigStructOutput], "view">;

  getProtocolFee: TypedContractMethod<[], [bigint], "view">;

  getSubscriptionBatchReader: TypedContractMethod<[], [string], "view">;

  initialize: TypedContractMethod<
    [_config: BillingConfigStruct],
    [void],
    "nonpayable"
  >;

  nodeResponded: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  prepareNextInterval: TypedContractMethod<
    [
      subscriptionId: BigNumberish,
      nextInterval: BigNumberish,
      nodeWallet: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  redundancyCount: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  reportComputeResult: TypedContractMethod<
    [
      deliveryInterval: BigNumberish,
      input: PayloadDataStruct,
      output: PayloadDataStruct,
      proof: PayloadDataStruct,
      commitmentData: BytesLike,
      nodeWallet: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  reportVerificationResult: TypedContractMethod<
    [request: ProofVerificationRequestStruct, valid: boolean],
    [void],
    "nonpayable"
  >;

  requestCommitments: TypedContractMethod<
    [requestId: BytesLike],
    [string],
    "view"
  >;

  setSubscriptionBatchReader: TypedContractMethod<
    [_reader: AddressLike],
    [void],
    "nonpayable"
  >;

  startRequest: TypedContractMethod<
    [
      requestId: BytesLike,
      subscriptionId: BigNumberish,
      containerId: BytesLike,
      interval: BigNumberish,
      redundancy: BigNumberish,
      useDeliveryInbox: boolean,
      feeToken: AddressLike,
      feeAmount: BigNumberish,
      wallet: AddressLike,
      verifier: AddressLike
    ],
    [CommitmentStructOutput],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [to: AddressLike],
    [void],
    "nonpayable"
  >;

  typeAndVersion: TypedContractMethod<[], [string], "view">;

  updateConfig: TypedContractMethod<
    [config: BillingConfigStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelRequest"
  ): TypedContractMethod<[requestId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "client"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getCommitment"
  ): TypedContractMethod<
    [subscriptionId: BigNumberish, interval: BigNumberish],
    [CommitmentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getConfig"
  ): TypedContractMethod<[], [BillingConfigStructOutput], "view">;
  getFunction(
    nameOrSignature: "getProtocolFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSubscriptionBatchReader"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[_config: BillingConfigStruct], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "nodeResponded"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "prepareNextInterval"
  ): TypedContractMethod<
    [
      subscriptionId: BigNumberish,
      nextInterval: BigNumberish,
      nodeWallet: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "redundancyCount"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "reportComputeResult"
  ): TypedContractMethod<
    [
      deliveryInterval: BigNumberish,
      input: PayloadDataStruct,
      output: PayloadDataStruct,
      proof: PayloadDataStruct,
      commitmentData: BytesLike,
      nodeWallet: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reportVerificationResult"
  ): TypedContractMethod<
    [request: ProofVerificationRequestStruct, valid: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestCommitments"
  ): TypedContractMethod<[requestId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "setSubscriptionBatchReader"
  ): TypedContractMethod<[_reader: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startRequest"
  ): TypedContractMethod<
    [
      requestId: BytesLike,
      subscriptionId: BigNumberish,
      containerId: BytesLike,
      interval: BigNumberish,
      redundancy: BigNumberish,
      useDeliveryInbox: boolean,
      feeToken: AddressLike,
      feeAmount: BigNumberish,
      wallet: AddressLike,
      verifier: AddressLike
    ],
    [CommitmentStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "typeAndVersion"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateConfig"
  ): TypedContractMethod<[config: BillingConfigStruct], [void], "nonpayable">;

  getEvent(
    key: "ComputeDelivered"
  ): TypedContractEvent<
    ComputeDeliveredEvent.InputTuple,
    ComputeDeliveredEvent.OutputTuple,
    ComputeDeliveredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferRequested"
  ): TypedContractEvent<
    OwnershipTransferRequestedEvent.InputTuple,
    OwnershipTransferRequestedEvent.OutputTuple,
    OwnershipTransferRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProofVerified"
  ): TypedContractEvent<
    ProofVerifiedEvent.InputTuple,
    ProofVerifiedEvent.OutputTuple,
    ProofVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "RequestCancelled"
  ): TypedContractEvent<
    RequestCancelledEvent.InputTuple,
    RequestCancelledEvent.OutputTuple,
    RequestCancelledEvent.OutputObject
  >;
  getEvent(
    key: "RequestStarted"
  ): TypedContractEvent<
    RequestStartedEvent.InputTuple,
    RequestStartedEvent.OutputTuple,
    RequestStartedEvent.OutputObject
  >;

  filters: {
    "ComputeDelivered(bytes32,address,uint16,tuple,tuple,tuple)": TypedContractEvent<
      ComputeDeliveredEvent.InputTuple,
      ComputeDeliveredEvent.OutputTuple,
      ComputeDeliveredEvent.OutputObject
    >;
    ComputeDelivered: TypedContractEvent<
      ComputeDeliveredEvent.InputTuple,
      ComputeDeliveredEvent.OutputTuple,
      ComputeDeliveredEvent.OutputObject
    >;

    "OwnershipTransferRequested(address,address)": TypedContractEvent<
      OwnershipTransferRequestedEvent.InputTuple,
      OwnershipTransferRequestedEvent.OutputTuple,
      OwnershipTransferRequestedEvent.OutputObject
    >;
    OwnershipTransferRequested: TypedContractEvent<
      OwnershipTransferRequestedEvent.InputTuple,
      OwnershipTransferRequestedEvent.OutputTuple,
      OwnershipTransferRequestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProofVerified(uint64,uint32,address,bool,address)": TypedContractEvent<
      ProofVerifiedEvent.InputTuple,
      ProofVerifiedEvent.OutputTuple,
      ProofVerifiedEvent.OutputObject
    >;
    ProofVerified: TypedContractEvent<
      ProofVerifiedEvent.InputTuple,
      ProofVerifiedEvent.OutputTuple,
      ProofVerifiedEvent.OutputObject
    >;

    "RequestCancelled(bytes32)": TypedContractEvent<
      RequestCancelledEvent.InputTuple,
      RequestCancelledEvent.OutputTuple,
      RequestCancelledEvent.OutputObject
    >;
    RequestCancelled: TypedContractEvent<
      RequestCancelledEvent.InputTuple,
      RequestCancelledEvent.OutputTuple,
      RequestCancelledEvent.OutputObject
    >;

    "RequestStarted(bytes32,uint64,bytes32,tuple)": TypedContractEvent<
      RequestStartedEvent.InputTuple,
      RequestStartedEvent.OutputTuple,
      RequestStartedEvent.OutputObject
    >;
    RequestStarted: TypedContractEvent<
      RequestStartedEvent.InputTuple,
      RequestStartedEvent.OutputTuple,
      RequestStartedEvent.OutputObject
    >;
  };
}
