/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export type ComputeSubscriptionStruct = {
  routeId: BytesLike;
  containerId: BytesLike;
  feeAmount: BigNumberish;
  client: AddressLike;
  activeAt: BigNumberish;
  intervalSeconds: BigNumberish;
  maxExecutions: BigNumberish;
  wallet: AddressLike;
  feeToken: AddressLike;
  verifier: AddressLike;
  useDeliveryInbox: boolean;
};

export type ComputeSubscriptionStructOutput = [
  routeId: string,
  containerId: string,
  feeAmount: bigint,
  client: string,
  activeAt: bigint,
  intervalSeconds: bigint,
  maxExecutions: bigint,
  wallet: string,
  feeToken: string,
  verifier: string,
  useDeliveryInbox: boolean
] & {
  routeId: string;
  containerId: string;
  feeAmount: bigint;
  client: string;
  activeAt: bigint;
  intervalSeconds: bigint;
  maxExecutions: bigint;
  wallet: string;
  feeToken: string;
  verifier: string;
  useDeliveryInbox: boolean;
};

export type PayloadDataStruct = { contentHash: BytesLike; uri: BytesLike };

export type PayloadDataStructOutput = [contentHash: string, uri: string] & {
  contentHash: string;
  uri: string;
};

export type PaymentStruct = {
  recipient: AddressLike;
  feeToken: AddressLike;
  feeAmount: BigNumberish;
};

export type PaymentStructOutput = [
  recipient: string,
  feeToken: string,
  feeAmount: bigint
] & { recipient: string; feeToken: string; feeAmount: bigint };

export type CommitmentStruct = {
  requestId: BytesLike;
  subscriptionId: BigNumberish;
  containerId: BytesLike;
  interval: BigNumberish;
  useDeliveryInbox: boolean;
  walletAddress: AddressLike;
  feeAmount: BigNumberish;
  feeToken: AddressLike;
  verifier: AddressLike;
  coordinator: AddressLike;
  verifierFee: BigNumberish;
};

export type CommitmentStructOutput = [
  requestId: string,
  subscriptionId: bigint,
  containerId: string,
  interval: bigint,
  useDeliveryInbox: boolean,
  walletAddress: string,
  feeAmount: bigint,
  feeToken: string,
  verifier: string,
  coordinator: string,
  verifierFee: bigint
] & {
  requestId: string;
  subscriptionId: bigint;
  containerId: string;
  interval: bigint;
  useDeliveryInbox: boolean;
  walletAddress: string;
  feeAmount: bigint;
  feeToken: string;
  verifier: string;
  coordinator: string;
  verifierFee: bigint;
};

export type ProofVerificationRequestStruct = {
  subscriptionId: BigNumberish;
  interval: BigNumberish;
  submitterAddress: AddressLike;
  submitterWallet: AddressLike;
  escrowedAmount: BigNumberish;
  escrowToken: AddressLike;
  slashAmount: BigNumberish;
  expiry: BigNumberish;
};

export type ProofVerificationRequestStructOutput = [
  subscriptionId: bigint,
  interval: bigint,
  submitterAddress: string,
  submitterWallet: string,
  escrowedAmount: bigint,
  escrowToken: string,
  slashAmount: bigint,
  expiry: bigint
] & {
  subscriptionId: bigint;
  interval: bigint;
  submitterAddress: string;
  submitterWallet: string;
  escrowedAmount: bigint;
  escrowToken: string;
  slashAmount: bigint;
  expiry: bigint;
};

export interface RouterAbiInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "EIP712_NAME"
      | "EIP712_VERSION"
      | "acceptOwnership"
      | "areValidWallets"
      | "callbackGasLimit"
      | "cancelComputeSubscription"
      | "client"
      | "createComputeSubscription"
      | "createSubscriptionDelegatee"
      | "createSubscriptionFor"
      | "delegateCreatedIds"
      | "eip712Domain"
      | "fulfill"
      | "getComputeSubscription"
      | "getComputeSubscriptionInterval"
      | "getContractById"
      | "getIntervalAndValidateWallets"
      | "getLastSubscriptionId"
      | "getProposedContractById"
      | "getWalletFactory"
      | "hasSubscriptionNextInterval"
      | "isValidWallet"
      | "lockForVerification"
      | "maxSubscriberNonce"
      | "minRepeatInterval"
      | "ownerCancelSubscription"
      | "pause"
      | "paused"
      | "payFromCoordinator"
      | "pendingRequestExists"
      | "prepareNodeVerification"
      | "proposeContractsUpdate"
      | "sendRequest"
      | "setCallbackGasLimit"
      | "setMinRepeatInterval"
      | "setWalletFactory"
      | "timeoutRequest"
      | "timeoutSubscriptionIntervalsUpTo"
      | "transferOwnership"
      | "typeAndVersion"
      | "unlockAndPayForVerification"
      | "unlockForVerification"
      | "unpause"
      | "updateContracts"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CallbackFailed"
      | "CallbackGasLimitSet"
      | "CommitmentTimedOut"
      | "ContractsUpdateProposed"
      | "ContractsUpdated"
      | "EIP712DomainChanged"
      | "MinRepeatIntervalSet"
      | "OwnershipTransferRequested"
      | "OwnershipTransferred"
      | "Paused"
      | "PaymentMade"
      | "RequestProcessed"
      | "RequestStart"
      | "SubscriptionCancelled"
      | "SubscriptionCreated"
      | "SubscriptionFulfilled"
      | "Unpaused"
      | "VerificationFundsLocked"
      | "VerificationFundsUnlocked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "EIP712_NAME",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EIP712_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "areValidWallets",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "callbackGasLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelComputeSubscription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "client", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createComputeSubscription",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      boolean,
      AddressLike,
      BigNumberish,
      AddressLike,
      AddressLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createSubscriptionDelegatee",
    values: [BigNumberish, BigNumberish, ComputeSubscriptionStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createSubscriptionFor",
    values: [ComputeSubscriptionStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "delegateCreatedIds",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fulfill",
    values: [
      PayloadDataStruct,
      PayloadDataStruct,
      PayloadDataStruct,
      AddressLike,
      PaymentStruct[],
      CommitmentStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getComputeSubscription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getComputeSubscriptionInterval",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getContractById",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getIntervalAndValidateWallets",
    values: [BigNumberish, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getLastSubscriptionId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProposedContractById",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWalletFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasSubscriptionNextInterval",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lockForVerification",
    values: [ProofVerificationRequestStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxSubscriberNonce",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "minRepeatInterval",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ownerCancelSubscription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payFromCoordinator",
    values: [BigNumberish, AddressLike, AddressLike, PaymentStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingRequestExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "prepareNodeVerification",
    values: [BigNumberish, BigNumberish, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeContractsUpdate",
    values: [BytesLike[], AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "sendRequest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCallbackGasLimit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinRepeatInterval",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setWalletFactory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "timeoutRequest",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "timeoutSubscriptionIntervalsUpTo",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "typeAndVersion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unlockAndPayForVerification",
    values: [
      ProofVerificationRequestStruct,
      AddressLike,
      AddressLike,
      PaymentStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockForVerification",
    values: [ProofVerificationRequestStruct]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateContracts",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "EIP712_NAME",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EIP712_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "areValidWallets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callbackGasLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelComputeSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "client", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createComputeSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSubscriptionDelegatee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSubscriptionFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "delegateCreatedIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fulfill", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getComputeSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getComputeSubscriptionInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIntervalAndValidateWallets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastSubscriptionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposedContractById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWalletFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasSubscriptionNextInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockForVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxSubscriberNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minRepeatInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerCancelSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payFromCoordinator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingRequestExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "prepareNodeVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeContractsUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCallbackGasLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinRepeatInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWalletFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timeoutRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timeoutSubscriptionIntervalsUpTo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "typeAndVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockAndPayForVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockForVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateContracts",
    data: BytesLike
  ): Result;
}

export namespace CallbackFailedEvent {
  export type InputTuple = [
    subscriptionId: BigNumberish,
    interval: BigNumberish,
    client: AddressLike
  ];
  export type OutputTuple = [
    subscriptionId: bigint,
    interval: bigint,
    client: string
  ];
  export interface OutputObject {
    subscriptionId: bigint;
    interval: bigint;
    client: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CallbackGasLimitSetEvent {
  export type InputTuple = [newCallbackGasLimit: BigNumberish];
  export type OutputTuple = [newCallbackGasLimit: bigint];
  export interface OutputObject {
    newCallbackGasLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CommitmentTimedOutEvent {
  export type InputTuple = [
    requestId: BytesLike,
    subscriptionId: BigNumberish,
    interval: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    subscriptionId: bigint,
    interval: bigint
  ];
  export interface OutputObject {
    requestId: string;
    subscriptionId: bigint;
    interval: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractsUpdateProposedEvent {
  export type InputTuple = [ids: BytesLike[], addresses: AddressLike[]];
  export type OutputTuple = [ids: string[], addresses: string[]];
  export interface OutputObject {
    ids: string[];
    addresses: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractsUpdatedEvent {
  export type InputTuple = [id: BytesLike, contractAddress: AddressLike];
  export type OutputTuple = [id: string, contractAddress: string];
  export interface OutputObject {
    id: string;
    contractAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinRepeatIntervalSetEvent {
  export type InputTuple = [newMinRepeatInterval: BigNumberish];
  export type OutputTuple = [newMinRepeatInterval: bigint];
  export interface OutputObject {
    newMinRepeatInterval: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferRequestedEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike];
  export type OutputTuple = [from: string, to: string];
  export interface OutputObject {
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike];
  export type OutputTuple = [from: string, to: string];
  export interface OutputObject {
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentMadeEvent {
  export type InputTuple = [
    subscriptionId: BigNumberish,
    spenderWallet: AddressLike,
    recipient: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    subscriptionId: bigint,
    spenderWallet: string,
    recipient: string,
    token: string,
    amount: bigint
  ];
  export interface OutputObject {
    subscriptionId: bigint;
    spenderWallet: string;
    recipient: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestProcessedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    subscriptionId: BigNumberish,
    containerId: BytesLike,
    interval: BigNumberish,
    useDeliveryInbox: boolean,
    feeAmount: BigNumberish,
    feeToken: AddressLike,
    verifier: AddressLike,
    coordinator: AddressLike,
    nodeWallet: AddressLike,
    result: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    subscriptionId: bigint,
    containerId: string,
    interval: bigint,
    useDeliveryInbox: boolean,
    feeAmount: bigint,
    feeToken: string,
    verifier: string,
    coordinator: string,
    nodeWallet: string,
    result: bigint
  ];
  export interface OutputObject {
    requestId: string;
    subscriptionId: bigint;
    containerId: string;
    interval: bigint;
    useDeliveryInbox: boolean;
    feeAmount: bigint;
    feeToken: string;
    verifier: string;
    coordinator: string;
    nodeWallet: string;
    result: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestStartEvent {
  export type InputTuple = [
    requestId: BytesLike,
    subscriptionId: BigNumberish,
    containerId: BytesLike,
    interval: BigNumberish,
    useDeliveryInbox: boolean,
    feeAmount: BigNumberish,
    feeToken: AddressLike,
    verifier: AddressLike,
    coordinator: AddressLike
  ];
  export type OutputTuple = [
    requestId: string,
    subscriptionId: bigint,
    containerId: string,
    interval: bigint,
    useDeliveryInbox: boolean,
    feeAmount: bigint,
    feeToken: string,
    verifier: string,
    coordinator: string
  ];
  export interface OutputObject {
    requestId: string;
    subscriptionId: bigint;
    containerId: string;
    interval: bigint;
    useDeliveryInbox: boolean;
    feeAmount: bigint;
    feeToken: string;
    verifier: string;
    coordinator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionCancelledEvent {
  export type InputTuple = [subscriptionId: BigNumberish];
  export type OutputTuple = [subscriptionId: bigint];
  export interface OutputObject {
    subscriptionId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionCreatedEvent {
  export type InputTuple = [subscriptionId: BigNumberish];
  export type OutputTuple = [subscriptionId: bigint];
  export interface OutputObject {
    subscriptionId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionFulfilledEvent {
  export type InputTuple = [id: BigNumberish, node: AddressLike];
  export type OutputTuple = [id: bigint, node: string];
  export interface OutputObject {
    id: bigint;
    node: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationFundsLockedEvent {
  export type InputTuple = [
    subscriptionId: BigNumberish,
    interval: BigNumberish,
    spender: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    subscriptionId: bigint,
    interval: bigint,
    spender: string,
    amount: bigint
  ];
  export interface OutputObject {
    subscriptionId: bigint;
    interval: bigint;
    spender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationFundsUnlockedEvent {
  export type InputTuple = [
    subscriptionId: BigNumberish,
    interval: BigNumberish,
    spender: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    subscriptionId: bigint,
    interval: bigint,
    spender: string,
    amount: bigint
  ];
  export interface OutputObject {
    subscriptionId: bigint;
    interval: bigint;
    spender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RouterAbi extends BaseContract {
  connect(runner?: ContractRunner | null): RouterAbi;
  waitForDeployment(): Promise<this>;

  interface: RouterAbiInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  EIP712_NAME: TypedContractMethod<[], [string], "view">;

  EIP712_VERSION: TypedContractMethod<[], [string], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  areValidWallets: TypedContractMethod<
    [walletAddrs: AddressLike[]],
    [boolean],
    "view"
  >;

  callbackGasLimit: TypedContractMethod<[], [bigint], "view">;

  cancelComputeSubscription: TypedContractMethod<
    [subscriptionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  client: TypedContractMethod<[], [string], "view">;

  createComputeSubscription: TypedContractMethod<
    [
      containerId: string,
      maxExecutions: BigNumberish,
      intervalSeconds: BigNumberish,
      useDeliveryInbox: boolean,
      feeToken: AddressLike,
      feeAmount: BigNumberish,
      wallet: AddressLike,
      verifier: AddressLike,
      routeId: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  createSubscriptionDelegatee: TypedContractMethod<
    [
      nonce: BigNumberish,
      expiry: BigNumberish,
      sub: ComputeSubscriptionStruct,
      signature: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  createSubscriptionFor: TypedContractMethod<
    [sub: ComputeSubscriptionStruct],
    [bigint],
    "nonpayable"
  >;

  delegateCreatedIds: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  fulfill: TypedContractMethod<
    [
      input: PayloadDataStruct,
      output: PayloadDataStruct,
      proof: PayloadDataStruct,
      nodeWallet: AddressLike,
      payments: PaymentStruct[],
      commitment: CommitmentStruct
    ],
    [bigint],
    "nonpayable"
  >;

  getComputeSubscription: TypedContractMethod<
    [subscriptionId: BigNumberish],
    [ComputeSubscriptionStructOutput],
    "view"
  >;

  getComputeSubscriptionInterval: TypedContractMethod<
    [subscriptionId: BigNumberish],
    [bigint],
    "view"
  >;

  getContractById: TypedContractMethod<[id: BytesLike], [string], "view">;

  getIntervalAndValidateWallets: TypedContractMethod<
    [subscriptionId: BigNumberish, walletAddrs: AddressLike[]],
    [[bigint, boolean] & { interval: bigint; allWalletsValid: boolean }],
    "view"
  >;

  getLastSubscriptionId: TypedContractMethod<[], [bigint], "view">;

  getProposedContractById: TypedContractMethod<
    [id: BytesLike],
    [string],
    "view"
  >;

  getWalletFactory: TypedContractMethod<[], [string], "view">;

  hasSubscriptionNextInterval: TypedContractMethod<
    [subscriptionId: BigNumberish, currentInterval: BigNumberish],
    [boolean],
    "view"
  >;

  isValidWallet: TypedContractMethod<
    [walletAddr: AddressLike],
    [boolean],
    "view"
  >;

  lockForVerification: TypedContractMethod<
    [proofRequest: ProofVerificationRequestStruct, commitmentHash: BytesLike],
    [void],
    "nonpayable"
  >;

  maxSubscriberNonce: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  minRepeatInterval: TypedContractMethod<[], [bigint], "view">;

  ownerCancelSubscription: TypedContractMethod<
    [subscriptionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  payFromCoordinator: TypedContractMethod<
    [
      subscriptionId: BigNumberish,
      spenderWallet: AddressLike,
      spenderAddress: AddressLike,
      payments: PaymentStruct[]
    ],
    [void],
    "nonpayable"
  >;

  pendingRequestExists: TypedContractMethod<
    [subscriptionId: BigNumberish],
    [boolean],
    "view"
  >;

  prepareNodeVerification: TypedContractMethod<
    [
      subscriptionId: BigNumberish,
      nextInterval: BigNumberish,
      nodeWallet: AddressLike,
      token: AddressLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  proposeContractsUpdate: TypedContractMethod<
    [proposalSetIds: BytesLike[], proposalSetAddresses: AddressLike[]],
    [void],
    "nonpayable"
  >;

  sendRequest: TypedContractMethod<
    [subscriptionId: BigNumberish, interval: BigNumberish],
    [[string, CommitmentStructOutput]],
    "nonpayable"
  >;

  setCallbackGasLimit: TypedContractMethod<
    [_callbackGasLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMinRepeatInterval: TypedContractMethod<
    [_minRepeatInterval: BigNumberish],
    [void],
    "nonpayable"
  >;

  setWalletFactory: TypedContractMethod<
    [_walletFactory: AddressLike],
    [void],
    "nonpayable"
  >;

  timeoutRequest: TypedContractMethod<
    [
      requestId: BytesLike,
      subscriptionId: BigNumberish,
      interval: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  timeoutSubscriptionIntervalsUpTo: TypedContractMethod<
    [
      subscriptionId: BigNumberish,
      uptoInterval: BigNumberish,
      maxIter: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [to: AddressLike],
    [void],
    "nonpayable"
  >;

  typeAndVersion: TypedContractMethod<[], [string], "view">;

  unlockAndPayForVerification: TypedContractMethod<
    [
      proofRequest: ProofVerificationRequestStruct,
      spenderWallet: AddressLike,
      spenderAddress: AddressLike,
      payments: PaymentStruct[]
    ],
    [void],
    "nonpayable"
  >;

  unlockForVerification: TypedContractMethod<
    [proofRequest: ProofVerificationRequestStruct],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateContracts: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "EIP712_NAME"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "EIP712_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "areValidWallets"
  ): TypedContractMethod<[walletAddrs: AddressLike[]], [boolean], "view">;
  getFunction(
    nameOrSignature: "callbackGasLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelComputeSubscription"
  ): TypedContractMethod<[subscriptionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "client"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createComputeSubscription"
  ): TypedContractMethod<
    [
      containerId: string,
      maxExecutions: BigNumberish,
      intervalSeconds: BigNumberish,
      useDeliveryInbox: boolean,
      feeToken: AddressLike,
      feeAmount: BigNumberish,
      wallet: AddressLike,
      verifier: AddressLike,
      routeId: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createSubscriptionDelegatee"
  ): TypedContractMethod<
    [
      nonce: BigNumberish,
      expiry: BigNumberish,
      sub: ComputeSubscriptionStruct,
      signature: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createSubscriptionFor"
  ): TypedContractMethod<
    [sub: ComputeSubscriptionStruct],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "delegateCreatedIds"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "fulfill"
  ): TypedContractMethod<
    [
      input: PayloadDataStruct,
      output: PayloadDataStruct,
      proof: PayloadDataStruct,
      nodeWallet: AddressLike,
      payments: PaymentStruct[],
      commitment: CommitmentStruct
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getComputeSubscription"
  ): TypedContractMethod<
    [subscriptionId: BigNumberish],
    [ComputeSubscriptionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getComputeSubscriptionInterval"
  ): TypedContractMethod<[subscriptionId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getContractById"
  ): TypedContractMethod<[id: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getIntervalAndValidateWallets"
  ): TypedContractMethod<
    [subscriptionId: BigNumberish, walletAddrs: AddressLike[]],
    [[bigint, boolean] & { interval: bigint; allWalletsValid: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLastSubscriptionId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProposedContractById"
  ): TypedContractMethod<[id: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getWalletFactory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "hasSubscriptionNextInterval"
  ): TypedContractMethod<
    [subscriptionId: BigNumberish, currentInterval: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isValidWallet"
  ): TypedContractMethod<[walletAddr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lockForVerification"
  ): TypedContractMethod<
    [proofRequest: ProofVerificationRequestStruct, commitmentHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "maxSubscriberNonce"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "minRepeatInterval"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ownerCancelSubscription"
  ): TypedContractMethod<[subscriptionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "payFromCoordinator"
  ): TypedContractMethod<
    [
      subscriptionId: BigNumberish,
      spenderWallet: AddressLike,
      spenderAddress: AddressLike,
      payments: PaymentStruct[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pendingRequestExists"
  ): TypedContractMethod<[subscriptionId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "prepareNodeVerification"
  ): TypedContractMethod<
    [
      subscriptionId: BigNumberish,
      nextInterval: BigNumberish,
      nodeWallet: AddressLike,
      token: AddressLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proposeContractsUpdate"
  ): TypedContractMethod<
    [proposalSetIds: BytesLike[], proposalSetAddresses: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sendRequest"
  ): TypedContractMethod<
    [subscriptionId: BigNumberish, interval: BigNumberish],
    [[string, CommitmentStructOutput]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCallbackGasLimit"
  ): TypedContractMethod<
    [_callbackGasLimit: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMinRepeatInterval"
  ): TypedContractMethod<
    [_minRepeatInterval: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setWalletFactory"
  ): TypedContractMethod<[_walletFactory: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "timeoutRequest"
  ): TypedContractMethod<
    [
      requestId: BytesLike,
      subscriptionId: BigNumberish,
      interval: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "timeoutSubscriptionIntervalsUpTo"
  ): TypedContractMethod<
    [
      subscriptionId: BigNumberish,
      uptoInterval: BigNumberish,
      maxIter: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "typeAndVersion"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unlockAndPayForVerification"
  ): TypedContractMethod<
    [
      proofRequest: ProofVerificationRequestStruct,
      spenderWallet: AddressLike,
      spenderAddress: AddressLike,
      payments: PaymentStruct[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unlockForVerification"
  ): TypedContractMethod<
    [proofRequest: ProofVerificationRequestStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateContracts"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "CallbackFailed"
  ): TypedContractEvent<
    CallbackFailedEvent.InputTuple,
    CallbackFailedEvent.OutputTuple,
    CallbackFailedEvent.OutputObject
  >;
  getEvent(
    key: "CallbackGasLimitSet"
  ): TypedContractEvent<
    CallbackGasLimitSetEvent.InputTuple,
    CallbackGasLimitSetEvent.OutputTuple,
    CallbackGasLimitSetEvent.OutputObject
  >;
  getEvent(
    key: "CommitmentTimedOut"
  ): TypedContractEvent<
    CommitmentTimedOutEvent.InputTuple,
    CommitmentTimedOutEvent.OutputTuple,
    CommitmentTimedOutEvent.OutputObject
  >;
  getEvent(
    key: "ContractsUpdateProposed"
  ): TypedContractEvent<
    ContractsUpdateProposedEvent.InputTuple,
    ContractsUpdateProposedEvent.OutputTuple,
    ContractsUpdateProposedEvent.OutputObject
  >;
  getEvent(
    key: "ContractsUpdated"
  ): TypedContractEvent<
    ContractsUpdatedEvent.InputTuple,
    ContractsUpdatedEvent.OutputTuple,
    ContractsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "MinRepeatIntervalSet"
  ): TypedContractEvent<
    MinRepeatIntervalSetEvent.InputTuple,
    MinRepeatIntervalSetEvent.OutputTuple,
    MinRepeatIntervalSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferRequested"
  ): TypedContractEvent<
    OwnershipTransferRequestedEvent.InputTuple,
    OwnershipTransferRequestedEvent.OutputTuple,
    OwnershipTransferRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentMade"
  ): TypedContractEvent<
    PaymentMadeEvent.InputTuple,
    PaymentMadeEvent.OutputTuple,
    PaymentMadeEvent.OutputObject
  >;
  getEvent(
    key: "RequestProcessed"
  ): TypedContractEvent<
    RequestProcessedEvent.InputTuple,
    RequestProcessedEvent.OutputTuple,
    RequestProcessedEvent.OutputObject
  >;
  getEvent(
    key: "RequestStart"
  ): TypedContractEvent<
    RequestStartEvent.InputTuple,
    RequestStartEvent.OutputTuple,
    RequestStartEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionCancelled"
  ): TypedContractEvent<
    SubscriptionCancelledEvent.InputTuple,
    SubscriptionCancelledEvent.OutputTuple,
    SubscriptionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionCreated"
  ): TypedContractEvent<
    SubscriptionCreatedEvent.InputTuple,
    SubscriptionCreatedEvent.OutputTuple,
    SubscriptionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionFulfilled"
  ): TypedContractEvent<
    SubscriptionFulfilledEvent.InputTuple,
    SubscriptionFulfilledEvent.OutputTuple,
    SubscriptionFulfilledEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationFundsLocked"
  ): TypedContractEvent<
    VerificationFundsLockedEvent.InputTuple,
    VerificationFundsLockedEvent.OutputTuple,
    VerificationFundsLockedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationFundsUnlocked"
  ): TypedContractEvent<
    VerificationFundsUnlockedEvent.InputTuple,
    VerificationFundsUnlockedEvent.OutputTuple,
    VerificationFundsUnlockedEvent.OutputObject
  >;

  filters: {
    "CallbackFailed(uint64,uint32,address)": TypedContractEvent<
      CallbackFailedEvent.InputTuple,
      CallbackFailedEvent.OutputTuple,
      CallbackFailedEvent.OutputObject
    >;
    CallbackFailed: TypedContractEvent<
      CallbackFailedEvent.InputTuple,
      CallbackFailedEvent.OutputTuple,
      CallbackFailedEvent.OutputObject
    >;

    "CallbackGasLimitSet(uint32)": TypedContractEvent<
      CallbackGasLimitSetEvent.InputTuple,
      CallbackGasLimitSetEvent.OutputTuple,
      CallbackGasLimitSetEvent.OutputObject
    >;
    CallbackGasLimitSet: TypedContractEvent<
      CallbackGasLimitSetEvent.InputTuple,
      CallbackGasLimitSetEvent.OutputTuple,
      CallbackGasLimitSetEvent.OutputObject
    >;

    "CommitmentTimedOut(bytes32,uint64,uint32)": TypedContractEvent<
      CommitmentTimedOutEvent.InputTuple,
      CommitmentTimedOutEvent.OutputTuple,
      CommitmentTimedOutEvent.OutputObject
    >;
    CommitmentTimedOut: TypedContractEvent<
      CommitmentTimedOutEvent.InputTuple,
      CommitmentTimedOutEvent.OutputTuple,
      CommitmentTimedOutEvent.OutputObject
    >;

    "ContractsUpdateProposed(bytes32[],address[])": TypedContractEvent<
      ContractsUpdateProposedEvent.InputTuple,
      ContractsUpdateProposedEvent.OutputTuple,
      ContractsUpdateProposedEvent.OutputObject
    >;
    ContractsUpdateProposed: TypedContractEvent<
      ContractsUpdateProposedEvent.InputTuple,
      ContractsUpdateProposedEvent.OutputTuple,
      ContractsUpdateProposedEvent.OutputObject
    >;

    "ContractsUpdated(bytes32,address)": TypedContractEvent<
      ContractsUpdatedEvent.InputTuple,
      ContractsUpdatedEvent.OutputTuple,
      ContractsUpdatedEvent.OutputObject
    >;
    ContractsUpdated: TypedContractEvent<
      ContractsUpdatedEvent.InputTuple,
      ContractsUpdatedEvent.OutputTuple,
      ContractsUpdatedEvent.OutputObject
    >;

    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "MinRepeatIntervalSet(uint32)": TypedContractEvent<
      MinRepeatIntervalSetEvent.InputTuple,
      MinRepeatIntervalSetEvent.OutputTuple,
      MinRepeatIntervalSetEvent.OutputObject
    >;
    MinRepeatIntervalSet: TypedContractEvent<
      MinRepeatIntervalSetEvent.InputTuple,
      MinRepeatIntervalSetEvent.OutputTuple,
      MinRepeatIntervalSetEvent.OutputObject
    >;

    "OwnershipTransferRequested(address,address)": TypedContractEvent<
      OwnershipTransferRequestedEvent.InputTuple,
      OwnershipTransferRequestedEvent.OutputTuple,
      OwnershipTransferRequestedEvent.OutputObject
    >;
    OwnershipTransferRequested: TypedContractEvent<
      OwnershipTransferRequestedEvent.InputTuple,
      OwnershipTransferRequestedEvent.OutputTuple,
      OwnershipTransferRequestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PaymentMade(uint64,address,address,address,uint256)": TypedContractEvent<
      PaymentMadeEvent.InputTuple,
      PaymentMadeEvent.OutputTuple,
      PaymentMadeEvent.OutputObject
    >;
    PaymentMade: TypedContractEvent<
      PaymentMadeEvent.InputTuple,
      PaymentMadeEvent.OutputTuple,
      PaymentMadeEvent.OutputObject
    >;

    "RequestProcessed(bytes32,uint64,bytes32,uint32,bool,uint256,address,address,address,address,uint8)": TypedContractEvent<
      RequestProcessedEvent.InputTuple,
      RequestProcessedEvent.OutputTuple,
      RequestProcessedEvent.OutputObject
    >;
    RequestProcessed: TypedContractEvent<
      RequestProcessedEvent.InputTuple,
      RequestProcessedEvent.OutputTuple,
      RequestProcessedEvent.OutputObject
    >;

    "RequestStart(bytes32,uint64,bytes32,uint32,bool,uint256,address,address,address)": TypedContractEvent<
      RequestStartEvent.InputTuple,
      RequestStartEvent.OutputTuple,
      RequestStartEvent.OutputObject
    >;
    RequestStart: TypedContractEvent<
      RequestStartEvent.InputTuple,
      RequestStartEvent.OutputTuple,
      RequestStartEvent.OutputObject
    >;

    "SubscriptionCancelled(uint64)": TypedContractEvent<
      SubscriptionCancelledEvent.InputTuple,
      SubscriptionCancelledEvent.OutputTuple,
      SubscriptionCancelledEvent.OutputObject
    >;
    SubscriptionCancelled: TypedContractEvent<
      SubscriptionCancelledEvent.InputTuple,
      SubscriptionCancelledEvent.OutputTuple,
      SubscriptionCancelledEvent.OutputObject
    >;

    "SubscriptionCreated(uint64)": TypedContractEvent<
      SubscriptionCreatedEvent.InputTuple,
      SubscriptionCreatedEvent.OutputTuple,
      SubscriptionCreatedEvent.OutputObject
    >;
    SubscriptionCreated: TypedContractEvent<
      SubscriptionCreatedEvent.InputTuple,
      SubscriptionCreatedEvent.OutputTuple,
      SubscriptionCreatedEvent.OutputObject
    >;

    "SubscriptionFulfilled(uint64,address)": TypedContractEvent<
      SubscriptionFulfilledEvent.InputTuple,
      SubscriptionFulfilledEvent.OutputTuple,
      SubscriptionFulfilledEvent.OutputObject
    >;
    SubscriptionFulfilled: TypedContractEvent<
      SubscriptionFulfilledEvent.InputTuple,
      SubscriptionFulfilledEvent.OutputTuple,
      SubscriptionFulfilledEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "VerificationFundsLocked(uint64,uint32,address,uint256)": TypedContractEvent<
      VerificationFundsLockedEvent.InputTuple,
      VerificationFundsLockedEvent.OutputTuple,
      VerificationFundsLockedEvent.OutputObject
    >;
    VerificationFundsLocked: TypedContractEvent<
      VerificationFundsLockedEvent.InputTuple,
      VerificationFundsLockedEvent.OutputTuple,
      VerificationFundsLockedEvent.OutputObject
    >;

    "VerificationFundsUnlocked(uint64,uint32,address,uint256)": TypedContractEvent<
      VerificationFundsUnlockedEvent.InputTuple,
      VerificationFundsUnlockedEvent.OutputTuple,
      VerificationFundsUnlockedEvent.OutputObject
    >;
    VerificationFundsUnlocked: TypedContractEvent<
      VerificationFundsUnlockedEvent.InputTuple,
      VerificationFundsUnlockedEvent.OutputTuple,
      VerificationFundsUnlockedEvent.OutputObject
    >;
  };
}
