/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from './common';

export type ComputeSubscriptionStruct = {
  routeId: BytesLike;
  containerId: BytesLike;
  feeAmount: BigNumberish;
  client: AddressLike;
  activeAt: BigNumberish;
  intervalSeconds: BigNumberish;
  maxExecutions: BigNumberish;
  wallet: AddressLike;
  feeToken: AddressLike;
  verifier: AddressLike;
  redundancy: BigNumberish;
  useDeliveryInbox: boolean;
};

export type ComputeSubscriptionStructOutput = [
  routeId: string,
  containerId: string,
  feeAmount: bigint,
  client: string,
  activeAt: bigint,
  intervalSeconds: bigint,
  maxExecutions: bigint,
  wallet: string,
  feeToken: string,
  verifier: string,
  redundancy: bigint,
  useDeliveryInbox: boolean,
] & {
  routeId: string;
  containerId: string;
  feeAmount: bigint;
  client: string;
  activeAt: bigint;
  intervalSeconds: bigint;
  maxExecutions: bigint;
  wallet: string;
  feeToken: string;
  verifier: string;
  redundancy: bigint;
  useDeliveryInbox: boolean;
};

export declare namespace SubscriptionBatchReader {
  export type IntervalStatusStruct = {
    redundancyCount: BigNumberish;
    commitmentExists: boolean;
  };

  export type IntervalStatusStructOutput = [redundancyCount: bigint, commitmentExists: boolean] & {
    redundancyCount: bigint;
    commitmentExists: boolean;
  };
}

export interface SubscriptionBatchReaderAbiInterface extends Interface {
  getFunction(nameOrSignature: 'getIntervalStatuses' | 'getSubscriptions'): FunctionFragment;

  encodeFunctionData(
    functionFragment: 'getIntervalStatuses',
    values: [BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: 'getSubscriptions',
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: 'getIntervalStatuses', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getSubscriptions', data: BytesLike): Result;
}

export interface SubscriptionBatchReaderAbi extends BaseContract {
  connect(runner?: ContractRunner | null): SubscriptionBatchReaderAbi;
  waitForDeployment(): Promise<this>;

  interface: SubscriptionBatchReaderAbiInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  getIntervalStatuses: TypedContractMethod<
    [ids: BigNumberish[], intervals: BigNumberish[]],
    [SubscriptionBatchReader.IntervalStatusStructOutput[]],
    'view'
  >;

  getSubscriptions: TypedContractMethod<
    [startId: BigNumberish, endId: BigNumberish],
    [ComputeSubscriptionStructOutput[]],
    'view'
  >;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(
    nameOrSignature: 'getIntervalStatuses'
  ): TypedContractMethod<
    [ids: BigNumberish[], intervals: BigNumberish[]],
    [SubscriptionBatchReader.IntervalStatusStructOutput[]],
    'view'
  >;
  getFunction(
    nameOrSignature: 'getSubscriptions'
  ): TypedContractMethod<
    [startId: BigNumberish, endId: BigNumberish],
    [ComputeSubscriptionStructOutput[]],
    'view'
  >;

  filters: {};
}
