/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export type PaymentStruct = {
  recipient: AddressLike;
  feeToken: AddressLike;
  feeAmount: BigNumberish;
};

export type PaymentStructOutput = [
  recipient: string,
  feeToken: string,
  feeAmount: bigint
] & { recipient: string; feeToken: string; feeAmount: bigint };

export interface WalletAbiInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allowance"
      | "approve"
      | "disburseForFulfillment"
      | "disburseForRequest"
      | "getSpenderInfo"
      | "isValidSignature"
      | "lockEscrow"
      | "lockForRequest"
      | "lockedOfRequest"
      | "owner"
      | "releaseEscrow"
      | "releaseForRequest"
      | "renounceOwnership"
      | "totalLockedFor"
      | "transferByRouter"
      | "transferOwnership"
      | "typeAndVersion"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "Deposit"
      | "Escrow"
      | "OwnershipTransferred"
      | "RequestDisbursed"
      | "RequestLocked"
      | "RequestReleased"
      | "Transfer"
      | "Withdraw"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disburseForFulfillment",
    values: [BytesLike, PaymentStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "disburseForRequest",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSpenderInfo",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidSignature",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lockEscrow",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lockForRequest",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lockedOfRequest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "releaseEscrow",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseForRequest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalLockedFor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferByRouter",
    values: [AddressLike, PaymentStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "typeAndVersion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disburseForFulfillment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disburseForRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSpenderInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lockEscrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lockForRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockedOfRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseForRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalLockedFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferByRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "typeAndVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    spender: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [spender: string, token: string, amount: bigint];
  export interface OutputObject {
    spender: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowEvent {
  export type InputTuple = [
    spender: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    locked: boolean
  ];
  export type OutputTuple = [
    spender: string,
    token: string,
    amount: bigint,
    locked: boolean
  ];
  export interface OutputObject {
    spender: string;
    token: string;
    amount: bigint;
    locked: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestDisbursedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    to: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    to: string,
    token: string,
    amount: bigint
  ];
  export interface OutputObject {
    requestId: string;
    to: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestLockedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    spender: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    spender: string,
    token: string,
    amount: bigint
  ];
  export interface OutputObject {
    requestId: string;
    spender: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestReleasedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    spender: AddressLike,
    token: AddressLike,
    amountRefunded: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    spender: string,
    token: string,
    amountRefunded: bigint
  ];
  export interface OutputObject {
    requestId: string;
    spender: string;
    token: string;
    amountRefunded: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    spender: AddressLike,
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    spender: string,
    token: string,
    to: string,
    amount: bigint
  ];
  export interface OutputObject {
    spender: string;
    token: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WalletAbi extends BaseContract {
  connect(runner?: ContractRunner | null): WalletAbi;
  waitForDeployment(): Promise<this>;

  interface: WalletAbiInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allowance: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  approve: TypedContractMethod<
    [spender: AddressLike, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  disburseForFulfillment: TypedContractMethod<
    [requestId: BytesLike, payments: PaymentStruct[]],
    [void],
    "nonpayable"
  >;

  disburseForRequest: TypedContractMethod<
    [requestId: BytesLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getSpenderInfo: TypedContractMethod<
    [spender: AddressLike, token: AddressLike],
    [[bigint, bigint] & { spenderAllowance: bigint; availableBalance: bigint }],
    "view"
  >;

  isValidSignature: TypedContractMethod<
    [hash_: BytesLike, signature_: BytesLike],
    [string],
    "view"
  >;

  lockEscrow: TypedContractMethod<
    [spender: AddressLike, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  lockForRequest: TypedContractMethod<
    [
      spender: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      requestId: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  lockedOfRequest: TypedContractMethod<
    [requestId: BytesLike],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  releaseEscrow: TypedContractMethod<
    [spender: AddressLike, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  releaseForRequest: TypedContractMethod<
    [requestId: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  totalLockedFor: TypedContractMethod<[token: AddressLike], [bigint], "view">;

  transferByRouter: TypedContractMethod<
    [spender: AddressLike, payments: PaymentStruct[]],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  typeAndVersion: TypedContractMethod<[], [string], "view">;

  withdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [spender: AddressLike, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disburseForFulfillment"
  ): TypedContractMethod<
    [requestId: BytesLike, payments: PaymentStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disburseForRequest"
  ): TypedContractMethod<
    [requestId: BytesLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getSpenderInfo"
  ): TypedContractMethod<
    [spender: AddressLike, token: AddressLike],
    [[bigint, bigint] & { spenderAllowance: bigint; availableBalance: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "isValidSignature"
  ): TypedContractMethod<
    [hash_: BytesLike, signature_: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "lockEscrow"
  ): TypedContractMethod<
    [spender: AddressLike, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lockForRequest"
  ): TypedContractMethod<
    [
      spender: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      requestId: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lockedOfRequest"
  ): TypedContractMethod<[requestId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "releaseEscrow"
  ): TypedContractMethod<
    [spender: AddressLike, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "releaseForRequest"
  ): TypedContractMethod<[requestId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalLockedFor"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferByRouter"
  ): TypedContractMethod<
    [spender: AddressLike, payments: PaymentStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "typeAndVersion"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "Escrow"
  ): TypedContractEvent<
    EscrowEvent.InputTuple,
    EscrowEvent.OutputTuple,
    EscrowEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RequestDisbursed"
  ): TypedContractEvent<
    RequestDisbursedEvent.InputTuple,
    RequestDisbursedEvent.OutputTuple,
    RequestDisbursedEvent.OutputObject
  >;
  getEvent(
    key: "RequestLocked"
  ): TypedContractEvent<
    RequestLockedEvent.InputTuple,
    RequestLockedEvent.OutputTuple,
    RequestLockedEvent.OutputObject
  >;
  getEvent(
    key: "RequestReleased"
  ): TypedContractEvent<
    RequestReleasedEvent.InputTuple,
    RequestReleasedEvent.OutputTuple,
    RequestReleasedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "Withdraw"
  ): TypedContractEvent<
    WithdrawEvent.InputTuple,
    WithdrawEvent.OutputTuple,
    WithdrawEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "Deposit(address,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "Escrow(address,address,uint256,bool)": TypedContractEvent<
      EscrowEvent.InputTuple,
      EscrowEvent.OutputTuple,
      EscrowEvent.OutputObject
    >;
    Escrow: TypedContractEvent<
      EscrowEvent.InputTuple,
      EscrowEvent.OutputTuple,
      EscrowEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RequestDisbursed(bytes32,address,address,uint256)": TypedContractEvent<
      RequestDisbursedEvent.InputTuple,
      RequestDisbursedEvent.OutputTuple,
      RequestDisbursedEvent.OutputObject
    >;
    RequestDisbursed: TypedContractEvent<
      RequestDisbursedEvent.InputTuple,
      RequestDisbursedEvent.OutputTuple,
      RequestDisbursedEvent.OutputObject
    >;

    "RequestLocked(bytes32,address,address,uint256)": TypedContractEvent<
      RequestLockedEvent.InputTuple,
      RequestLockedEvent.OutputTuple,
      RequestLockedEvent.OutputObject
    >;
    RequestLocked: TypedContractEvent<
      RequestLockedEvent.InputTuple,
      RequestLockedEvent.OutputTuple,
      RequestLockedEvent.OutputObject
    >;

    "RequestReleased(bytes32,address,address,uint256)": TypedContractEvent<
      RequestReleasedEvent.InputTuple,
      RequestReleasedEvent.OutputTuple,
      RequestReleasedEvent.OutputObject
    >;
    RequestReleased: TypedContractEvent<
      RequestReleasedEvent.InputTuple,
      RequestReleasedEvent.OutputTuple,
      RequestReleasedEvent.OutputObject
    >;

    "Transfer(address,address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "Withdraw(address,uint256)": TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
    Withdraw: TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
  };
}
